server:
  url: http://api.koreatechmap.kro.kr

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/v1/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  servers:
    - url: http://api.koreatechmap.kro.kr
      description: 프로덕션 서버

logging:
  level:
    root: WARN
    kr.kro.koreatechmap: INFO 