server:
  url: https://api.koreatechmap.kro.kr

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  servers:
    - url: https://api.koreatechmap.kro.kr
      description: 프로덕션 서버

logging:
  level:
    root: WARN
    kr.kro.koreatechmap: INFO 